[phases.setup]
nixPkgs = ["php", "phpExtensions.pdo_mysql", "phpExtensions.mbstring", "composer"]

[phases.build]
cmds = [
    "composer install --optimize-autoloader --no-dev --no-interaction",
    "mkdir -p bootstrap/cache storage/framework/sessions storage/framework/views storage/framework/cache storage/logs",
    "chmod -R 775 bootstrap/cache storage",
]

[start]
cmd = "sh railway/start.sh"