<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class StatistikDokumen extends Model
{
    use HasFactory, SoftDeletes, HasUuids;

    public const BULAN_INDONESIA = [
        1 => 'Januari',
        2 => 'Februari',
        3 => 'Maret',
        4 => 'April',
        5 => 'Mei',
        6 => 'Juni',
        7 => 'Juli',
        8 => 'Agustus',
        9 => 'September',
        10 => 'Oktober',
        11 => 'November',
        12 => 'Desember',
    ];

    /** Lima layanan utama Disdukcapil Toba */
    public const JENIS_LAYANAN = [
        'jumlah_kk' => 'Kartu Keluarga',
        'jumlah_akte_lahir' => 'Kelahiran',
        'jumlah_akte_kematian' => 'Kematian',
        'jumlah_lahir_mati' => 'Lahir Mati',
        'jumlah_pernikahan' => 'Pernikahan',
    ];

    protected $table = 'statistik_dokumen';

    protected $primaryKey = 'statistik_dokumen_id';

    public $incrementing = false;

    protected $keyType = 'string';

    protected $fillable = [
        'tahun',
        'bulan',
        'jumlah_kk',
        'jumlah_akte_lahir',
        'jumlah_akte_kematian',
        'jumlah_lahir_mati',
        'jumlah_pernikahan',
        'total_dokumen',
        'is_auto_generated',
        'generated_at',
    ];

    protected $casts = [
        'tahun' => 'integer',
        'bulan' => 'integer',
        'jumlah_kk' => 'integer',
        'jumlah_akte_lahir' => 'integer',
        'jumlah_akte_kematian' => 'integer',
        'jumlah_lahir_mati' => 'integer',
        'jumlah_pernikahan' => 'integer',
        'total_dokumen' => 'integer',
        'is_auto_generated' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];

    public function scopeTahun($query, int $tahun)
    {
        return $query->where('tahun', $tahun);
    }

    public function scopeBulan($query, int $bulan)
    {
        return $query->where('bulan', $bulan);
    }

    public function scopePeriode($query, int $tahun, int $bulan)
    {
        return $query->where('tahun', $tahun)->where('bulan', $bulan);
    }

    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    public function scopeTerbaru($query)
    {
        return $query->orderBy('tahun', 'desc')->orderBy('bulan', 'desc');
    }

    public function scopeUrutPeriode($query)
    {
        return $query->orderBy('tahun', 'desc')->orderBy('bulan', 'desc');
    }

    public function getNamaBulanAttribute(): string
    {
        return self::BULAN_INDONESIA[$this->bulan] ?? '';
    }

    public function getPeriodeFormattedAttribute(): string
    {
        return $this->nama_bulan . ' ' . $this->tahun;
    }

    public function getTotalDokumenFormattedAttribute(): string
    {
        return number_format($this->total_dokumen, 0, ',', '.');
    }

    public static function hitungTotalDokumen(array $data): int
    {
        return collect(array_keys(self::JENIS_LAYANAN))
            ->sum(fn (string $field) => (int) ($data[$field] ?? 0));
    }

    protected static function boot(): void
    {
        parent::boot();

        static::saving(function ($model) {
            $model->total_dokumen = self::hitungTotalDokumen($model->getAttributes());
        });
    }
}
